# -*- coding: utf-8 -*-
"""Email Spam Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hzy9P0pLNDRpcKOQOSbJoJIrjGEgLIHr

# **Email spam Detection**
Email spam detection system is used to detect email spam using Machine Learning technique called Natural Language Processing and Python,
where we have a dataset contain a lot of emails by extract important words and then use naive classifier we can detect if this email is spam or not.

### **Libraries**
"""

import pickle
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_style("white")
import matplotlib.pyplot as plt
import string
from pickle import dump
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import nltk
from nltk.corpus import stopwords
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
nltk.download('stopwords')

from google.colab import drive
drive.mount('/content/drive')

# Load the dataset
dataset = pd.read_csv('/content/emails.csv')
dataset.shape

# Show dataset head (first 5 records)
dataset.head()

# Show dataset info
dataset.info()

# Show dataset statistics
dataset.describe()

"""##### **2. Data Visualization**
Visualize dataset features frequencies to get some insights
"""

# Visualize spam  frequenices
plt.figure(dpi=100)
sns.countplot(dataset['spam'])
plt.title("Spam Freqencies")
plt.show()

"""##### **3. Data Cleaning**
Handling missing values and check for duplicates
"""

# Check for missing data for each column
dataset.isnull().sum()

# Check for duplicates and remove them
dataset.drop_duplicates(inplace=True)

# Cleaning data from punctuation and stopwords and then tokenizing it into words (tokens)
def process(text):
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    clean = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean

# Fit the CountVectorizer to data
message = CountVectorizer(analyzer=process).fit_transform(dataset['text'])

# Save the vectorizer
dump(message, open("/content/vectorizer.pkl", "wb"))

"""##### **4. Data Splitting**
Split the dataset into training and testing sets
"""

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(message, dataset['spam'], test_size=0.20, random_state=0)

"""## **3. The Model**
In this phase we will create and train a multinomial naive bayes model
"""

# Model saving
dump(model, open("/content/model.pkl", 'wb'))

